<?php

function weekhours_menu() {
  $items = array();
  $items['admin/config/regional/weekhours'] = array(
    'title' => 'Weekhours settings',
    'description' => 'Please provide a regular week hour schedule',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('weekhours_admin'),
    'access arguments' => array('administer weekhours settings'),
    'type' => MENU_NORMAL_ITEM,
   );
  return $items;
}

function weekhours_admin() {

	$weekhours = _get_weekhours();
	
  $form = array();
  $form['mon'] = array(
    '#type' => 'fieldset',
    '#title' => t('Monday'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t("Time format example: 8:45AM, 11:45PM"),
  );
  $form['mon']['mon_open'] = array(
    '#type' => 'textfield',
    '#title' => t('Open'),
    '#default_value' => $weekhours['mon_open'],
    '#placeholder' => '8:45AM',
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );
  $form['mon']['mon_close'] = array(
    '#type' => 'textfield',
    '#title' => t('Close'),
    '#default_value' => $weekhours['mon_close'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );

  $form['tue'] = array(
    '#type' => 'fieldset',
    '#title' => t('Tuesday'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t("Time format example: 8:45AM, 11:45PM"),
  );
  $form['tue']['tue_open'] = array(
    '#type' => 'textfield',
    '#title' => t('Open'),
    '#default_value' => $weekhours['tue_open'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );
  $form['tue']['tue_close'] = array(
    '#type' => 'textfield',
    '#title' => t('Close'),
    '#default_value' => $weekhours['tue_close'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );

  $form['wed'] = array(
    '#type' => 'fieldset',
    '#title' => t('Wednesday'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t("Time format example: 8:45AM, 11:45PM"),
  );
  $form['wed']['wed_open'] = array(
    '#type' => 'textfield',
    '#title' => t('Open'),
    '#default_value' => $weekhours['wed_open'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );
  $form['wed']['wed_close'] = array(
    '#type' => 'textfield',
    '#title' => t('Close'),
    '#default_value' => $weekhours['wed_close'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );

  $form['thu'] = array(
    '#type' => 'fieldset',
    '#title' => t('Thursday'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t("Time format example: 8:45AM, 11:45PM"),
  );
  $form['thu']['thu_open'] = array(
    '#type' => 'textfield',
    '#title' => t('Open'),
    '#default_value' => $weekhours['thu_open'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );
  $form['thu']['thu_close'] = array(
    '#type' => 'textfield',
    '#title' => t('Close'),
    '#default_value' => $weekhours['thu_close'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );

  $form['fri'] = array(
    '#type' => 'fieldset',
    '#title' => t('Friday'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t("Time format example: 8:45AM, 9:45PM"),
  );
  $form['fri']['fri_open'] = array(
    '#type' => 'textfield',
    '#title' => t('Open'),
    '#default_value' => $weekhours['fri_open'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );
  $form['fri']['fri_close'] = array(
    '#type' => 'textfield',
    '#title' => t('Close'),
    '#default_value' => $weekhours['fri_close'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );

  $form['sat'] = array(
    '#type' => 'fieldset',
    '#title' => t('Saturday'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t("Time format example: 10:00AM, 9:45PM"),
  );
  $form['sat']['sat_open'] = array(
    '#type' => 'textfield',
    '#title' => t('Open'),
    '#default_value' => $weekhours['sat_open'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );
  $form['sat']['sat_close'] = array(
    '#type' => 'textfield',
    '#title' => t('Close'),
    '#default_value' => $weekhours['sat_close'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );

  $form['sun'] = array(
    '#type' => 'fieldset',
    '#title' => t('Sunday'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#description' => t("Time format example: 1:00PM, 11:45PM"),
  );
  $form['sun']['sun_open'] = array(
    '#type' => 'textfield',
    '#title' => t('Open'),
    '#default_value' => $weekhours['sun_open'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );
  $form['sun']['sun_close'] = array(
    '#type' => 'textfield',
    '#title' => t('Close'),
    '#default_value' => $weekhours['sun_close'],
    '#size' => 7,
    '#maxlength' => 7,
    '#required' => TRUE,
  );
  
  $form = system_settings_form($form);
  $form['#submit'] = array('weekhours_admin_submit');
  return $form;
}

function weekhours_admin_validate($form, &$form_state) {
// proper validation needs to be built
// Regular expresstion to check correct format as well as correct hour and minute information 
}

function weekhours_admin_submit($form, &$form_state) {

	$values = array();
	foreach($form_state['values'] as $key => $value){
		$values[$key] = $value;
		if($key == 'sun_close') break; 		
	} 
	
	variable_set('weekhours', $values);
}


/**
* Implements hook_block_info().
*/
function weekhours_block_info() {
  $blocks = array();
  $blocks['weekhours'] = array(
    'info' => t('Weekly Hour Block'),
  );
  return $blocks;
}
/**
* Implements hook_block_view().
*/
function weekhours_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'weekhours':
      $block['subject'] = '';
      $block['content'] = _weekhours_content();
      break;
  }
  return $block;
}
function _weekhours_content() {

	$weekhours = _get_weekhours(); $sd = ' - ';
	$week['mon'] = array('start' => $weekhours['mon_open'], 'end' => $weekhours['mon_close'], 'description' => $sd);
	$week['tue'] = array('start' => $weekhours['tue_open'], 'end' => $weekhours['tue_close'], 'description' => $sd);
	$week['wed'] = array('start' => $weekhours['wed_open'], 'end' => $weekhours['wed_close'], 'description' => $sd);
	$week['thu'] = array('start' => $weekhours['thu_open'], 'end' => $weekhours['thu_close'], 'description' => $sd);
	$week['fri'] = array('start' => $weekhours['fri_open'], 'end' => $weekhours['fri_close'], 'description' => $sd);
	$week['sat'] = array('start' => $weekhours['sat_open'], 'end' => $weekhours['sat_close'], 'description' => $sd);
	$week['sun'] = array('start' => $weekhours['sun_open'], 'end' => $weekhours['sun_close'], 'description' => $sd);

	$thismonday = strtotime('monday this week');
	$nextmonday = strtotime('monday next week');
	//dsm('this monday : '.$thismonday.' (gmdate->'.gmdate("Ymd H:i", $thismonday).' ) '.' (date->'.date("Ymd H:i", $thismonday).' ) ');
	//dsm('next monday : '.$nextmonday.' (gmdate->'.gmdate("Ymd H:i", $nextmonday).' ) '.' (date->'.date("Ymd H:i", $nextmonday).' ) ');

	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'node')
	  ->entityCondition('bundle', 'weekhour')
	  ->fieldCondition('field_wh_datetime', 'value', $nextmonday, '<')
	  ->fieldCondition('field_wh_datetime', 'value', $thismonday, '>')
	  ->fieldOrderBy('field_wh_datetime', 'value', 'ASC');
	$result = $query->execute();
	//	dsm($result);	
	if (isset($result['node'])) {
		  $node_nids = array_keys($result['node']);
		  $nodes = entity_load('node', $node_nids);
	}

	//dsm($nodes);
	foreach($nodes as $node){
		$start = $node->field_wh_datetime['und'][0]['value']; $end = $node->field_wh_datetime['und'][0]['value2'];
		$weekday = strtolower(date("D", $start)); //$weekday = date("D Ymd g:iA", $start);
		if($week[$weekday]){
			if($start == $end){
				$week[$weekday]['start'] = '';	
				$week[$weekday]['end'] = '<span class="closed"> CLOSED</span>';
				$week[$weekday]['description'] = '';
			}
			else
			{
				$week[$weekday]['start'] = date("g:iA", $start);	
				$week[$weekday]['end'] = date("g:iA", $end);
			}
			
			if(isset($node->field_wh_description['und'][0]['value'])) $week[$weekday]['start'] = '<span class="weekhour-description">('.$node->field_wh_description['und'][0]['value'].')</span>'.$week[$weekday]['start'];
			
			// attach edit button if the user has Edit access for the node
			if(node_access("update", $node, $GLOBALS['user']) === true) $week[$weekday]['start'] .= '<span class="weekhour-edit"><a href="'.url('node/'.$node->nid.'/edit', array('query' => drupal_get_destination())).'">EDIT</a></span>';
			
		}
		//dsm(date("D Ymd g:iA", $node->field_wh_datetime['und'][0]['value']).' to '.date("D Ymd g:iA", $node->field_wh_datetime['und'][0]['value2']));
		//dsm(date("D Ymd g:iA", $node->field_wh_datetime['und'][0]['value']));
	}
	$output = '	
		<div class="weekhours-container">
			<div class="oneweekhours">    
				<div class="mon"><span class="weekday">Mon: </span><span class="openhours">'.$week['mon']['start'].$week['mon']['description'].$week['mon']['end'].'</span></div>
				<div class="tue"><span class="weekday">Tue: </span><span class="openhours">'.$week['tue']['start'].$week['tue']['description'].$week['tue']['end'].'</span></div>		
				<div class="wed"><span class="weekday">Wed: </span><span class="openhours">'.$week['wed']['start'].$week['wed']['description'].$week['wed']['end'].'</span></div>		
				<div class="thu"><span class="weekday">Thu: </span><span class="openhours">'.$week['thu']['start'].$week['thu']['description'].$week['thu']['end'].'</span></div>		
				<div class="fri"><span class="weekday">Fri: </span><span class="openhours">'.$week['fri']['start'].$week['fri']['description'].$week['fri']['end'].'</span></div>		
				<div class="sat"><span class="weekday">Sat: </span><span class="openhours">'.$week['sat']['start'].$week['sat']['description'].$week['sat']['end'].'</span></div>		
				<div class="sun"><span class="weekday">Sun: </span><span class="openhours">'.$week['sun']['start'].$week['sun']['description'].$week['sun']['end'].'</span></div>		
			</div>
		</div>
	';
  return $output;
}

function _get_weekhours(){
	$weekhours = variable_get('weekhours');
	if(empty($weekhours)){
		$weekhours['mon_open'] = '8:45AM';	$weekhours['mon_close'] = '11:45PM';
		$weekhours['tue_open'] = '8:45AM';	$weekhours['tue_close'] = '11:45PM';
		$weekhours['wed_open'] = '8:45AM';	$weekhours['wed_close'] = '11:45PM';
		$weekhours['thu_open'] = '8:45AM';	$weekhours['thu_close'] = '11:45PM';
		$weekhours['fri_open'] = '8:45AM';	$weekhours['fri_close'] = '9:45PM';
		$weekhours['sat_open'] = '10:00AM';	$weekhours['sat_close'] = '9:45PM';
		$weekhours['sun_open'] = '1:00PAM';	$weekhours['sun_close'] = '11:45PM';
	}
	return $weekhours;
}

